/* eslint-disable prettier/prettier */
export default {
  OPEN_NAV: 'OPEN_X_NAV',
  CLOSE_NAV: 'CLOSE_X_NAV',
  CLOSE_NAV_REDUCER: 'CLOSE_NAV_REDUCER',
  OPEN_NAV_REDUCER: 'OPEN_NAV_REDUCER',
  LOG_OUT: 'LOG_OUT',
  LOG_OUT_REDUCER: 'LOG_OUT_REDUCER',
  //---------------------------------
  LOADING_ACTION: 'LOADING_ACTION',
  //AUTH
  REGISTER_ACTION: 'REGISTER_ACTION',
  LOGIN_ACTION: 'LOGIN_ACTION',
  LOGOUT_ACTION: 'LOGOUT_ACTION',
  LOGIN_SUCCESS_ACTION: 'LOGIN_SUCCESS_ACTION',
  REFRESH_TOKEN_ACTION: 'REFRESH_TOKEN_ACTION',
  FORGOT_REQUEST_ACTION: 'FORGOT_REQUEST_ACTION',
  FORGOT_CONFIRM_ACTION: 'FORGOT_CONFIRM_ACTION',
  LOGIN_SOCIAL_NETWORK_ACTION: 'LOGIN_SOCIAL_NETWORK_ACTION',

  //ACCOUNT
  GET_CURRENT_ACCOUNT_ACTION: 'GET_CURRENT_ACCOUNT_ACTION',
  GET_CURRENT_ACCOUNT_SUCCESS: 'GET_CURRENT_ACCOUNT_SUCCESS',
  GET_CURRENT_ACCOUNT_FAILD: 'GET_CURRENT_ACCOUNT_FAILD',
  SEND_FEEDBACK_ACTION: 'SEND_FEEDBACK_ACTION',
  UPDATE_ACCOUNT_ACTION: 'UPDATE_ACCOUNT_ACTION',
  UPLOAD_FILE_ACTION: 'UPLOAD_FILE_ACTION',
  UPDATE_AVATAR_ACTION: 'UPDATE_AVATAR_ACTION',

  //GENERAL
  USER_GUIDE: 'USER_GUIDE',
  ABOUT_US: 'ABOUT_US',

  //LEARN
  GET_LIST_COURSE: 'GET_LIST_COURSE',
  GET_LIST_LESSON: 'GET_LIST_LESSON',
};
