/* eslint-disable prettier/prettier */
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const COURSE_SCREEN = 'COURSE_SCREEN';
export const GIFT_SCREEN = 'GIFT_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const SHOP_SCREEN = 'SHOP_SCREEN';
export const ALL_COURSES_SCREEN = 'ALL_COURSES_SCREEN';
export const LEARN_SKILLCHOOSE_SCREEN = 'LEARN_SKILLCHOOSE_SCREEN';
export const LEARN_AUDIO_SCREEN = 'LEARN_AUDIO_SCREEN';
export const LEARN_PRACTICE_SCREEN = 'LEARN_PRACTICE_SCREEN';
export const LEARN_SPEAK_SCREEN = 'LEARN_SPEAK_SCREEN';
export const LEARN_FLASHCARD_SCREEN = 'LEARN_FLASHCARD_SCREEN';
export const LEARN_WRITING_SCREEN = 'LEARN_WRITING_SCREEN';
export const LEARN_PRACTICE_RESULT_SCREEN = 'LEARN_PRACTICE_RESULT_SCREEN';
export const KNOWLEDGE_SCREEN = 'KNOWLEDGE_SCREEN';

//Setting
export const CATEGOTY_SETTING_SCREEN = 'CATEGOTY_SETTING_SCREEN';
export const SETTING_SCREEN = 'SETTING_SCREEN';
export const ABOUT_US_SCREEN = 'ABOUT_US_SCREEN';
export const USER_GUIDE_SCREEN = 'USER_GUIDE_SCREEN';
export const TERM_OF_SERVICE = 'TERM_OF_SERVICE';

//for test
export const TEST_SCREEN = 'TEST_SCREEN';
