export const lightTheme = {
  PRIMARY_BACKGROUND_COLOR: '#F6F6F6',
  SECONDARY_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR: '#424242',
  SECONDARY_TEXT_COLOR: '#424242',
  PRIMARY_TEXTINPUT_COLOR: '#FFFFFF',
  PRIMARY_BUTTON_COLOR: '#23C115',
  PRIMARY_BUTTON_TEXT_COLOR: '#F6F6F9',
  PRIMARY_BG_WHITE_COLOR: '#FFFFFF',
  STATUS_BAR_STYLE: 'default',
  BACK_ICON_COLOR: 'black',
  BOTTOM_BAR_BG_COLOR: '#FFFFFF',
  BG_CARD_COLOR: '#FFFFFF',
};

export const darkTheme = {
  PRIMARY_BACKGROUND_COLOR: '#303234',
  SECONDARY_BACKGROUND_COLOR: '#646667',
  PRIMARY_TEXT_COLOR: '#B3B3B3',
  SECONDARY_TEXT_COLOR: '#FFFFFF',
  PRIMARY_TEXTINPUT_COLOR: '#646667',
  PRIMARY_BUTTON_COLOR: '#23C115',
  PRIMARY_BUTTON_TEXT_COLOR: 'red',
  PRIMARY_BG_WHITE_COLOR: 'black',
  STATUS_BAR_STYLE: 'light-content',
  BACK_ICON_COLOR: '#B3B3B3',
  BOTTOM_BAR_BG_COLOR: '#303234',
  BG_CARD_COLOR: '#444444',
};
